version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for each microservices
          command: |
            echo "--------- Installing dependencies-----------"
            sudo curl -LO https://nodejs.org/dist/v12.22.12/node-v12.22.12-linux-x64.tar.xz
            sudo tar -xvf node-v12.22.12-linux-x64.tar.xz
            sudo cp -r node-v12.22.12-linux-x64/{bin,include,lib,share} /usr/
            node --version => v12.22.12 
            sudo apt install nodejs
            echo "--------- The images is Building ------------"
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed tanui1998/udagram-api-feed:v4
            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user tanui1998/udagram-api-user:v4
            
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend tanui1998/udagram-frontend:v4
            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy tanui1998/udagram-reverseproxy:v4
            echo "-------- All images succesfully built----------"
            echo " ------- login in to hub--------"
            docker login -u tanui1998 -p $DOCKERPASS
            echo "-------------- Pushing images to dockerhub-------"
            docker push tanui1998/udagram-api-feed:v4
            docker push tanui1998/udagram-api-user:v4
            docker push tanui1998/udagram-frontend:v4
            docker push tanui1998/udagram-reverseproxy:v4
workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]